export const data = {
  AF: { id: "1", name: "Afghanistan", calling_code: "+93", phone_length: "9" },
  AL: { id: "2", name: "Albania", calling_code: "+355", phone_length: "9" },
  DZ: { id: "3", name: "Algeria", calling_code: "+213", phone_length: "9" },
  AD: { id: "4", name: "Andorra", calling_code: "+376", phone_length: "6" },
  AO: { id: "5", name: "Angola", calling_code: "+244", phone_length: "9" },
  AG: {
    id: "6",
    name: "Antigua and Barbuda",
    calling_code: "+1",
    phone_length: "10",
  },
  AR: { id: "7", name: "Argentina", calling_code: "+54", phone_length: "10" },
  AM: { id: "8", name: "Armenia", calling_code: "+374", phone_length: "8" },
  AU: { id: "9", name: "Australia", calling_code: "+61", phone_length: "9" },
  AT: { id: "10", name: "Austria", calling_code: "+43", phone_length: "10" },
  AZ: { id: "11", name: "Azerbaijan", calling_code: "+994", phone_length: "9" },
  BS: { id: "12", name: "Bahamas", calling_code: "+1", phone_length: "10" },
  BH: { id: "13", name: "Bahrain", calling_code: "+973", phone_length: "8" },
  BD: {
    id: "14",
    name: "Bangladesh",
    calling_code: "+880",
    phone_length: "10",
  },
  BB: { id: "15", name: "Barbados", calling_code: "+1", phone_length: "10" },
  BY: { id: "16", name: "Belarus", calling_code: "+375", phone_length: "9" },
  BE: { id: "17", name: "Belgium", calling_code: "+32", phone_length: "9" },
  BZ: { id: "18", name: "Belize", calling_code: "+501", phone_length: "7" },
  BJ: { id: "19", name: "Benin", calling_code: "+229", phone_length: "8" },
  BT: { id: "20", name: "Bhutan", calling_code: "+975", phone_length: "8" },
  BO: { id: "21", name: "Bolivia", calling_code: "+591", phone_length: "8" },
  BA: {
    id: "22",
    name: "Bosnia and Herzegovina",
    calling_code: "+387",
    phone_length: "8",
  },
  BW: { id: "23", name: "Botswana", calling_code: "+267", phone_length: "7" },
  BR: { id: "24", name: "Brazil", calling_code: "+55", phone_length: "11" },
  BN: {
    id: "25",
    name: "Brunei Darussalam",
    calling_code: "+673",
    phone_length: "7",
  },
  BG: { id: "26", name: "Bulgaria", calling_code: "+359", phone_length: "9" },
  BF: {
    id: "27",
    name: "Burkina Faso",
    calling_code: "+226",
    phone_length: "8",
  },
  BI: { id: "28", name: "Burundi", calling_code: "+257", phone_length: "8" },
  KH: { id: "29", name: "Cambodia", calling_code: "+855", phone_length: "9" },
  CM: { id: "30", name: "Cameroon", calling_code: "+237", phone_length: "9" },
  CA: { id: "31", name: "Canada", calling_code: "+1", phone_length: "10" },
  CV: { id: "32", name: "Cape Verde", calling_code: "+238", phone_length: "7" },
  CF: {
    id: "33",
    name: "Central African Republic",
    calling_code: "+236",
    phone_length: "8",
  },
  TD: { id: "34", name: "Chad", calling_code: "+235", phone_length: "8" },
  CL: { id: "35", name: "Chile", calling_code: "+56", phone_length: "9" },
  CN: { id: "36", name: "China", calling_code: "+86", phone_length: "11" },
  CO: { id: "37", name: "Colombia", calling_code: "+57", phone_length: "10" },
  KM: { id: "38", name: "Comoros", calling_code: "+269", phone_length: "7" },
  CG: { id: "39", name: "Congo", calling_code: "+242", phone_length: "9" },
  CD: {
    id: "40",
    name: "Congo (Democratic Republic)",
    calling_code: "+243",
    phone_length: "9",
  },
  CR: { id: "41", name: "Costa Rica", calling_code: "+506", phone_length: "8" },
  HR: { id: "42", name: "Croatia", calling_code: "+385", phone_length: "9" },
  CU: { id: "43", name: "Cuba", calling_code: "+53", phone_length: "8" },
  CY: { id: "44", name: "Cyprus", calling_code: "+357", phone_length: "8" },
  CZ: {
    id: "45",
    name: "Czech Republic",
    calling_code: "+420",
    phone_length: "9",
  },
  DK: { id: "46", name: "Denmark", calling_code: "+45", phone_length: "8" },
  DJ: { id: "47", name: "Djibouti", calling_code: "+253", phone_length: "8" },
  DM: { id: "48", name: "Dominica", calling_code: "+1", phone_length: "10" },
  DO: {
    id: "49",
    name: "Dominican Republic",
    calling_code: "+1",
    phone_length: "10",
  },
  EC: { id: "50", name: "Ecuador", calling_code: "+593", phone_length: "9" },
  EG: { id: "51", name: "Egypt", calling_code: "+20", phone_length: "10" },
  SV: {
    id: "52",
    name: "El Salvador",
    calling_code: "+503",
    phone_length: "8",
  },
  GQ: {
    id: "53",
    name: "Equatorial Guinea",
    calling_code: "+240",
    phone_length: "9",
  },
  ER: { id: "54", name: "Eritrea", calling_code: "+291", phone_length: "7" },
  EE: { id: "55", name: "Estonia", calling_code: "+372", phone_length: "9" },
  SZ: { id: "56", name: "Eswatini", calling_code: "+268", phone_length: "7" },
  ET: { id: "57", name: "Ethiopia", calling_code: "+251", phone_length: "9" },
  FJ: { id: "58", name: "Fiji", calling_code: "+679", phone_length: "7" },
  FI: { id: "59", name: "Finland", calling_code: "+358", phone_length: "9" },
  FR: { id: "60", name: "France", calling_code: "+33", phone_length: "9" },
  GA: { id: "61", name: "Gabon", calling_code: "+241", phone_length: "8" },
  GM: { id: "62", name: "Gambia", calling_code: "+220", phone_length: "7" },

  GE: { id: "63", name: "Georgia", calling_code: "+995", phone_length: "9" },
  DE: { id: "64", name: "Germany", calling_code: "+49", phone_length: "10" },
  GH: { id: "65", name: "Ghana", calling_code: "+233", phone_length: "9" },
  GR: { id: "66", name: "Greece", calling_code: "+30", phone_length: "10" },
  GD: { id: "67", name: "Grenada", calling_code: "+1", phone_length: "10" },
  GT: { id: "68", name: "Guatemala", calling_code: "+502", phone_length: "8" },
  GN: { id: "69", name: "Guinea", calling_code: "+224", phone_length: "9" },
  GW: {
    id: "70",
    name: "Guinea-Bissau",
    calling_code: "+245",
    phone_length: "7",
  },
  GY: { id: "71", name: "Guyana", calling_code: "+592", phone_length: "7" },
  HT: { id: "72", name: "Haiti", calling_code: "+509", phone_length: "8" },
  HN: { id: "73", name: "Honduras", calling_code: "+504", phone_length: "8" },
  HU: { id: "74", name: "Hungary", calling_code: "+36", phone_length: "9" },
  IS: { id: "75", name: "Iceland", calling_code: "+354", phone_length: "7" },
  ID: { id: "76", name: "Indonesia", calling_code: "+62", phone_length: "10" },
  IR: { id: "77", name: "Iran", calling_code: "+98", phone_length: "10" },
  IQ: { id: "78", name: "Iraq", calling_code: "+964", phone_length: "10" },
  IE: { id: "79", name: "Ireland", calling_code: "+353", phone_length: "9" },
  IL: { id: "80", name: "Israel", calling_code: "+972", phone_length: "9" },
  IT: { id: "81", name: "Italy", calling_code: "+39", phone_length: "10" },
  JM: { id: "82", name: "Jamaica", calling_code: "+1", phone_length: "10" },
  JP: { id: "83", name: "Japan", calling_code: "+81", phone_length: "10" },
  JO: { id: "84", name: "Jordan", calling_code: "+962", phone_length: "9" },
  KZ: { id: "85", name: "Kazakhstan", calling_code: "+7", phone_length: "10" },
  KE: { id: "86", name: "Kenya", calling_code: "+254", phone_length: "9" },
  KI: { id: "87", name: "Kiribati", calling_code: "+686", phone_length: "5" },
  KP: {
    id: "88",
    name: "Korea (North)",
    calling_code: "+850",
    phone_length: "9",
  },
  KR: {
    id: "89",
    name: "Korea (South)",
    calling_code: "+82",
    phone_length: "9",
  },
  KW: { id: "90", name: "Kuwait", calling_code: "+965", phone_length: "8" },
  KG: { id: "91", name: "Kyrgyzstan", calling_code: "+996", phone_length: "9" },
  LA: { id: "92", name: "Laos", calling_code: "+856", phone_length: "9" },
  LV: { id: "93", name: "Latvia", calling_code: "+371", phone_length: "8" },
  LB: { id: "94", name: "Lebanon", calling_code: "+961", phone_length: "8" },
  LS: { id: "95", name: "Lesotho", calling_code: "+266", phone_length: "9" },
  LR: { id: "96", name: "Liberia", calling_code: "+231", phone_length: "7" },
  LY: { id: "97", name: "Libya", calling_code: "+218", phone_length: "9" },
  LI: {
    id: "98",
    name: "Liechtenstein",
    calling_code: "+423",
    phone_length: "7",
  },
  LT: { id: "99", name: "Lithuania", calling_code: "+370", phone_length: "8" },
  LU: {
    id: "100",
    name: "Luxembourg",
    calling_code: "+352",
    phone_length: "9",
  },
  MG: {
    id: "101",
    name: "Madagascar",
    calling_code: "+261",
    phone_length: "9",
  },
  MW: { id: "102", name: "Malawi", calling_code: "+265", phone_length: "9" },
  MY: { id: "103", name: "Malaysia", calling_code: "+60", phone_length: "10" },
  MV: { id: "104", name: "Maldives", calling_code: "+960", phone_length: "7" },
  ML: { id: "105", name: "Mali", calling_code: "+223", phone_length: "8" },
  MT: { id: "106", name: "Malta", calling_code: "+356", phone_length: "8" },
  MH: {
    id: "107",
    name: "Marshall Islands",
    calling_code: "+692",
    phone_length: "7",
  },
  MR: {
    id: "108",
    name: "Mauritania",
    calling_code: "+222",
    phone_length: "8",
  },
  MU: { id: "109", name: "Mauritius", calling_code: "+230", phone_length: "8" },
  MX: { id: "110", name: "Mexico", calling_code: "+52", phone_length: "10" },
  FM: {
    id: "111",
    name: "Micronesia",
    calling_code: "+691",
    phone_length: "7",
  },
  MD: { id: "112", name: "Moldova", calling_code: "+373", phone_length: "8" },
  MC: { id: "113", name: "Monaco", calling_code: "+377", phone_length: "9" },
  MN: { id: "114", name: "Mongolia", calling_code: "+976", phone_length: "8" },
  ME: {
    id: "115",
    name: "Montenegro",
    calling_code: "+382",
    phone_length: "9",
  },
  MA: { id: "116", name: "Morocco", calling_code: "+212", phone_length: "9" },
  MZ: {
    id: "117",
    name: "Mozambique",
    calling_code: "+258",
    phone_length: "9",
  },
  MM: { id: "118", name: "Myanmar", calling_code: "+95", phone_length: "9" },

  NA: { id: "119", name: "Namibia", calling_code: "+264", phone_length: "9" },
  NR: { id: "120", name: "Nauru", calling_code: "+674", phone_length: "8" },
  NP: { id: "121", name: "Nepal", calling_code: "+977", phone_length: "10" },
  NL: {
    id: "122",
    name: "Netherlands",
    calling_code: "+31",
    phone_length: "9",
  },
  NZ: {
    id: "123",
    name: "New Zealand",
    calling_code: "+64",
    phone_length: "9",
  },
  NI: { id: "124", name: "Nicaragua", calling_code: "+505", phone_length: "8" },
  NE: { id: "125", name: "Niger", calling_code: "+227", phone_length: "10" },
  NG: { id: "126", name: "Nigeria", calling_code: "+234", phone_length: "10" },
  MK: {
    id: "127",
    name: "North Macedonia",
    calling_code: "+389",
    phone_length: "9",
  },
  NO: { id: "128", name: "Norway", calling_code: "+47", phone_length: "8" },
  OM: { id: "129", name: "Oman", calling_code: "+968", phone_length: "8" },
  PK: { id: "130", name: "Pakistan", calling_code: "+92", phone_length: "10" },
  PW: { id: "131", name: "Palau", calling_code: "+680", phone_length: "7" },
  PS: { id: "132", name: "Palestine", calling_code: "+970", phone_length: "9" },
  PA: { id: "133", name: "Panama", calling_code: "+507", phone_length: "7" },
  PG: {
    id: "134",
    name: "Papua New Guinea",
    calling_code: "+675",
    phone_length: "10",
  },
  PY: { id: "135", name: "Paraguay", calling_code: "+595", phone_length: "9" },
  PE: { id: "136", name: "Peru", calling_code: "+51", phone_length: "9" },
  PH: {
    id: "137",
    name: "Philippines",
    calling_code: "+63",
    phone_length: "10",
  },
  PL: { id: "138", name: "Poland", calling_code: "+48", phone_length: "9" },
  PT: { id: "139", name: "Portugal", calling_code: "+351", phone_length: "9" },
  QA: { id: "140", name: "Qatar", calling_code: "+974", phone_length: "8" },
  RE: { id: "141", name: "Réunion", calling_code: "+262", phone_length: "10" },
  RO: { id: "142", name: "Romania", calling_code: "+40", phone_length: "10" },
  RU: { id: "143", name: "Russia", calling_code: "+7", phone_length: "10" },
  RW: { id: "144", name: "Rwanda", calling_code: "+250", phone_length: "10" },
  BL: {
    id: "145",
    name: "Saint Barthélemy",
    calling_code: "+590",
    phone_length: "10",
  },
  KN: {
    id: "146",
    name: "Saint Kitts and Nevis",
    calling_code: "+1",
    phone_length: "10",
  },
  LC: {
    id: "147",
    name: "Saint Lucia",
    calling_code: "+1",
    phone_length: "10",
  },
  MF: {
    id: "148",
    name: "Saint Martin",
    calling_code: "+590",
    phone_length: "10",
  },
  SX: {
    id: "149",
    name: "Sint Maarten",
    calling_code: "+1",
    phone_length: "10",
  },
  VC: {
    id: "150",
    name: "Saint Vincent and the Grenadines",
    calling_code: "+1",
    phone_length: "10",
  },
  WS: { id: "151", name: "Samoa", calling_code: "+685", phone_length: "7" },
  SM: {
    id: "152",
    name: "San Marino",
    calling_code: "+378",
    phone_length: "10",
  },
  ST: {
    id: "153",
    name: "São Tomé and Príncipe",
    calling_code: "+239",
    phone_length: "7",
  },
  SA: {
    id: "154",
    name: "Saudi Arabia",
    calling_code: "+966",
    phone_length: "9",
  },
  SN: { id: "155", name: "Senegal", calling_code: "+221", phone_length: "9" },
  RS: { id: "156", name: "Serbia", calling_code: "+381", phone_length: "9" },
  SC: {
    id: "157",
    name: "Seychelles",
    calling_code: "+248",
    phone_length: "7",
  },
  SL: {
    id: "158",
    name: "Sierra Leone",
    calling_code: "+232",
    phone_length: "8",
  },
  SG: { id: "159", name: "Singapore", calling_code: "+65", phone_length: "8" },
  SK: { id: "160", name: "Slovakia", calling_code: "+421", phone_length: "9" },
  SI: { id: "161", name: "Slovenia", calling_code: "+386", phone_length: "8" },
  SB: {
    id: "162",
    name: "Solomon Islands",
    calling_code: "+677",
    phone_length: "7",
  },
  SO: { id: "163", name: "Somalia", calling_code: "+252", phone_length: "9" },
  ZA: {
    id: "164",
    name: "South Africa",
    calling_code: "+27",
    phone_length: "10",
  },
  SS: {
    id: "165",
    name: "South Sudan",
    calling_code: "+211",
    phone_length: "9",
  },
  ES: { id: "166", name: "Spain", calling_code: "+34", phone_length: "9" },
  LK: { id: "167", name: "Sri Lanka", calling_code: "+94", phone_length: "10" },
  SD: { id: "168", name: "Sudan", calling_code: "+249", phone_length: "10" },
  SR: { id: "169", name: "Suriname", calling_code: "+597", phone_length: "7" },
  SE: { id: "171", name: "Sweden", calling_code: "+46", phone_length: "10" },
  CH: {
    id: "172",
    name: "Switzerland",
    calling_code: "+41",
    phone_length: "10",
  },
  SY: { id: "173", name: "Syria", calling_code: "+963", phone_length: "9" },
  TJ: {
    id: "174",
    name: "Tajikistan",
    calling_code: "+992",
    phone_length: "9",
  },
  TZ: { id: "175", name: "Tanzania", calling_code: "+255", phone_length: "10" },
  TH: { id: "176", name: "Thailand", calling_code: "+66", phone_length: "9" },
  TG: { id: "177", name: "Togo", calling_code: "+228", phone_length: "8" },
  TK: { id: "178", name: "Tokelau", calling_code: "+690", phone_length: "5" },
  TO: { id: "179", name: "Tonga", calling_code: "+676", phone_length: "7" },
  TT: {
    id: "180",
    name: "Trinidad and Tobago",
    calling_code: "+1",
    phone_length: "10",
  },
  TN: { id: "181", name: "Tunisia", calling_code: "+216", phone_length: "8" },
  TR: { id: "182", name: "Turkey", calling_code: "+90", phone_length: "10" },
  TM: {
    id: "183",
    name: "Turkmenistan",
    calling_code: "+993",
    phone_length: "9",
  },
  TC: {
    id: "184",
    name: "Turks and Caicos Islands",
    calling_code: "+1",
    phone_length: "10",
  },
  TV: { id: "185", name: "Tuvalu", calling_code: "+688", phone_length: "7" },
  UG: { id: "186", name: "Uganda", calling_code: "+256", phone_length: "10" },
  UA: { id: "187", name: "Ukraine", calling_code: "+380", phone_length: "9" },
  AE: {
    id: "188",
    name: "United Arab Emirates",
    calling_code: "+971",
    phone_length: "9",
  },
  GB: {
    id: "189",
    name: "United Kingdom",
    calling_code: "+44",
    phone_length: "10",
  },
  US: {
    id: "190",
    name: "United States",
    calling_code: "+1",
    phone_length: "10",
  },
  UY: { id: "191", name: "Uruguay", calling_code: "+598", phone_length: "8" },
  UZ: {
    id: "192",
    name: "Uzbekistan",
    calling_code: "+998",
    phone_length: "9",
  },
  VU: { id: "193", name: "Vanuatu", calling_code: "+678", phone_length: "7" },
  VE: { id: "194", name: "Venezuela", calling_code: "+58", phone_length: "10" },
  VN: { id: "195", name: "Vietnam", calling_code: "+84", phone_length: "10" },
  WF: {
    id: "196",
    name: "Wallis and Futuna",
    calling_code: "+681",
    phone_length: "7",
  },
  YE: { id: "197", name: "Yemen", calling_code: "+967", phone_length: "9" },
  ZM: { id: "198", name: "Zambia", calling_code: "+260", phone_length: "10" },
  ZW: { id: "199", name: "Zimbabwe", calling_code: "+263", phone_length: "9" },
};
